import {createFileRoute} from '@tanstack/react-router';
import {useState} from 'react';
import {ArrowUpRight, Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {StudioHeader, StudioFooter} from '@/components/studio/studio';
import {services, studioHead} from '@/components/studio/data';
import french from '@/assets/nails-french.jpg';
import {WhatsAppButton} from '@/components/studio/studio-choices';
export const Route=createFileRoute('/agendamento')({head:()=>studioHead('Seu próximo momento — Space LaBelle','Escolha o cuidado que combina com você e prepare seu próximo momento na Space LaBelle.'),component:BookingPage});
function BookingPage(){const[summary,setSummary]=useState<{name:string;service:string;date:string}|null>(null);return <><StudioHeader/><main className="section"><div className="booking-layout"><div><span className="eyebrow">Um encontro com você</span><h1 className="editorial-title">Seu próximo<br/><em>momento.</em></h1><p className="section-subtitle">Escolha seu cuidado. O resto é deixar a criatividade florescer.</p>{summary?<div className="selection-summary" role="status"><Check className="text-primary"/><h3>Sua escolha, {summary.name}.</h3><p>{summary.service}<br/>Data desejada: {summary.date.split('-').reverse().join('/')}</p><p>Esta é uma prévia da sua escolha, não uma reserva. A agenda do studio ainda não está conectada.</p><Button variant="quiet" onClick={()=>setSummary(null)}>Alterar minha escolha</Button></div>:<form className="booking-form" onSubmit={e=>{e.preventDefault();const data=new FormData(e.currentTarget);setSummary({name:String(data.get('name')),service:String(data.get('service')),date:String(data.get('date'))})}}><label className="field">Seu nome<input name="name" placeholder="Como podemos te chamar?" required autoComplete="given-name" maxLength={80}/></label><label className="field">Seu cuidado<select name="service" required><option value="">Selecione um serviço</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></label><label className="field">Data desejada<input type="date" name="date" required/></label><Button variant="studio" type="submit">Revisar minha escolha <ArrowUpRight/></Button><p className="booking-note">A agenda ainda não está conectada. Você pode explorar os serviços e revisar sua escolha, sem efetuar uma reserva.</p></form>}<div className="booking-whatsapp"><WhatsAppButton message={summary ? `Olá! Sou ${summary.name} e gostaria de ${summary.service}. Minha data desejada é ${summary.date.split('-').reverse().join('/')}. Há disponibilidade?` : undefined}/><p>Horários e reserva são combinados diretamente na conversa.</p></div></div><img className="booking-art" src={french} alt="Francesinha delicada com acabamento em gel" width={800} height={1008}/></div></main><StudioFooter/></>}