import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Heart, Sparkles } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { designs, services } from './data';
import { WhatsAppButton } from './studio-choices';
export function Wordmark() { return <Link to="/" className="wordmark" aria-label="Space LaBelle, início">Space LaBelle<small>nail design studio</small></Link>; }
export function StudioHeader() { return <header className="studio-header"><Wordmark/><nav className="studio-nav" aria-label="Navegação principal"><Link to="/catalogo">Catálogo</Link><Link to="/servicos">Serviços</Link><Link to="/agendamento">Agendamento</Link></nav><Button variant="studio" asChild><Link to="/agendamento">Seu próximo momento <ArrowUpRight/></Link></Button></header>; }
export function StudioFooter() { return <footer className="studio-footer"><Wordmark/><p>Feito com cuidado.<br/>Pensado para você.</p></footer>; }
export function Catalog({full=false}:{full?:boolean}) {
 const [filter,setFilter]=useState('Todas'); const [favorites,setFavorites]=useState<string[]>([]); const [selected,setSelected]=useState<(typeof designs)[number]|null>(null);
 return <section className="section"><div className="section-heading"><div><span className="eyebrow">Um pouco de inspiração</span><h2 className="editorial-title">Qual é a sua vibe?</h2></div>{!full&&<Button variant="quiet" asChild><Link to="/catalogo">Explorar catálogo <ArrowUpRight/></Link></Button>}</div>{full&&<div className="filter-bar">{['Todas','Clássicas','Cores','Nail art'].map(item=><Button key={item} variant="quiet" aria-pressed={filter===item} className={filter===item?'selected':''} onClick={()=>setFilter(item)}>{item}</Button>)}</div>}<div className="catalog-grid">{designs.filter(d=>filter==='Todas'||d.category===filter).map(d=><article className="nail-item" key={d.id}><div className="nail-image-wrap"><img src={d.image} alt={d.name} width={800} height={1008} loading="lazy"/><Button variant="quiet" size="icon" className="favorite" aria-label={`Favoritar ${d.name}`} aria-pressed={favorites.includes(d.id)} onClick={()=>setFavorites(prev=>prev.includes(d.id)?prev.filter(id=>id!==d.id):[...prev,d.id])}><Heart fill={favorites.includes(d.id)?'currentColor':'none'}/></Button></div><div className="nail-item-footer"><h3>{d.name}</h3><Button variant="quiet" size="icon" aria-label={`Ver ${d.name}`} onClick={()=>setSelected(d)}><ArrowUpRight/></Button></div><p>{d.detail}</p></article>)}</div><Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent>{selected&&<><DialogTitle>{selected.name}</DialogTitle><DialogDescription>{selected.detail}</DialogDescription><img src={selected.image} alt={selected.name} className="booking-art" width={800} height={1008}/><Button variant="studio" asChild><Link to="/agendamento">Escolher este estilo <ArrowUpRight/></Link></Button></>}</DialogContent></Dialog></section>;
}
export function Services(){return <section className="section services-band"><span className="eyebrow">Cuidado em cada detalhe</span><h2 className="editorial-title">Além das unhas.<br/>Um momento seu.</h2><div className="service-list">{services.map((s,i)=><article className="service-row" key={s.name}><span className="service-number">0{i+1}</span><div><h3>{s.name}</h3><p>{s.detail}</p></div><Button variant="quiet" size="icon" className="service-action" asChild><Link to="/agendamento" aria-label={`Agendar ${s.name}`}><ArrowUpRight/></Link></Button></article>)}</div></section>}
export function BookingBand(){return <section className="booking-band"><span className="eyebrow"><Sparkles size={12}/> Seu momento de pausa</span><h2 className="editorial-title">Vamos criar algo<br/><em>lindo juntas?</em></h2><div className="booking-actions"><Button variant="studio" asChild><Link to="/agendamento">Quero meu momento <ArrowUpRight/></Link></Button><WhatsAppButton /></div></section>}